### ISSUE TITLE
wasm: Uncaught TypeError: Error resolving module specifier “env”

### ISSUE THREAD

**Issue by schell** [smol-rs/fastrand#34] opened 2022-08-30 07:49 UTC
I've run into an interesting bug where attempting to run a wasm32-compiled program with `fastrand` in it gives this error in the console: 

```
Uncaught TypeError: Error resolving module specifier “env”. Relative module specifiers must start with “./”, “../” or “/”.
```

I'm using `fastrand = "1.8.0"`

I encountered this after adding `futures-lite` to my project, which depends on `fastrand`. https://github.com/rustwasm/wasm-bindgen/issues/2215 explains a few reasons why this error might pop up. 

I got around this problem by using `futures_lite::StreamExt::or` instead of `futures_lite::StreamExt::race`. `race` uses `fastrand::bool`, whereas `or` does not.

**Comment by taiki-e** [comment] 2022-08-30 07:52
Duplicate of #27

**Closed by taiki-e** 2022-08-30 07:52 UTC

**Comment by notgull** [comment] 2022-08-30 18:32
Note that if you compile and run the program in a WASI environment, it should all work out.
