### ISSUE TITLE
Rng::with_seed does not create reproducible results

### ISSUE THREAD

**Issue by malachid** [smol-rs/fastrand#45] opened 2023-01-28 07:15 UTC
If you create a seeded generator using:
```
fastrand::seed(num)
println!("{}", fastrand::u8(0..50));
```
the value will be reproducible with each run.

If you instead do:
```
fastrand::Rng::with_seed(num)
println!("{}", fastrand::u8(0..50));
```
the value will be different on every run.

I believe the intention is that setting a seed would make runs reproducible.

**Comment by taiki-e** [comment] 2023-01-28 07:33
- `fastrand::seed` changes seed of *thread local `Rng`*.
- `fastrand::Rng::with_seed` creates *a new instance of `Rng`* with the specified seed.
- `fastrand::u8` uses thread local `Rng` to generate u8.

I.e., in the second example, the seed is not actually changed.

**Comment by taiki-e** [comment] 2023-01-28 07:42
Close as it is working as intended. Once https://github.com/smol-rs/fastrand/pull/46 is merged, the compiler will show a useful warning in such cases.

```
warning: unused return value of `Rng::with_seed` that must be used
  --> tests/smoke.rs:35:5
   |
35 |     fastrand::Rng::with_seed(1);
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this creates a new instance of `Rng`; if you want to initialize the thread-local generator, use `fastrand::seed()` instead
```

**Closed by taiki-e** 2023-01-28 07:42 UTC

**Comment by malachid** [comment] 2023-01-28 07:52
Thanks for the quick clarification!
