### ISSUE TITLE
Global rng doesn't work in webassembly

### ISSUE THREAD

**Issue by dullbananas** [smol-rs/fastrand#57] opened 2023-03-25 16:16 UTC
When using the global rng functions (such as fastrand::u8 instead of fastrand::Rng::u8) or Rng::new, it fails because it tries to import "env" at runtime (#34). This should be fixed or mentioned in the docs.

**Comment by taiki-e** [comment] 2023-04-07 19:36
Duplicate of https://github.com/smol-rs/fastrand/issues/27

**Closed by taiki-e** 2023-04-07 19:36 UTC
